version: "3.2"
services:
  php-dynamic-qrcode:
    image: "giandonatoinverso/php-dynamic-qr-code:latest"
    restart: "unless-stopped"
    environment:
      TYPE: "docker"
      BASE_URL: "https://qr.prisma-group.ch"
      DATABASE_HOST: "qrcode_db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "qrcode"
      DATABASE_USER: "qrcode"
      DATABASE_PASSWORD: "changeme"
      DATABASE_PREFIX: ""
      DATABASE_CHARSET: "utf8"
    volumes:
      - data:/var/www/html/saved_qrcode
    networks:
      - qrcode-network
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  db:
    image: "giandonatoinverso/php-dynamic-qr-code-db:latest"
    restart: "unless-stopped"
    volumes:
      - php_dynamic_qrcode_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "qrcode"
      MYSQL_USER: "qrcode"
      MYSQL_PASSWORD: "changeme"
    networks:
      - qrcode-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          
networks:
  qrcode-network:
    driver: overlay
  proxy:
    external: true

volumes:
 php_dynamic_qrcode_db_data:
  driver: local
  driver_opts:
      type: "nfs"
      o: "addr=172.16.100.103,rw,bg,hard,vers=4,proto=tcp,timeo=600,rsize=65536,wsize=65536,nointr"
      device: ":/DOCKER/qrcode/db"
 data:
  driver: local
  driver_opts:
      type: "nfs"
      o: "addr=172.16.100.103,rw,bg,hard,vers=4,proto=tcp,timeo=600,rsize=65536,wsize=65536,nointr"
      device: ":/DOCKER/qrcode/data"
